import { StringDictionary } from "./types";

export const GroupToNameMapping: StringDictionary<string> = {
  "Azur Lane": "AzurLane: ",
  "Kill la Kill": "KillLaKill: ",
  "Blend S": "BlendS: ",
  "Guilty Crown": "GuiltyCrown: ",
  "Code Geass": "CodeGeass: ",
  "Helpful Fox Senko-san": "Senko-san: ",
  "Charlotte": "Charlotte: ",
  "Toaru Majutsu no Index" : "Railgun: ",
  "The Rising of Shield Hero" : "ShieldHero: ",
  "Chuunibyou" : "Chuunibyou: ",
  "One Punch Man": "OPM: ",
  "Shokugeki no Soma": "Shokugeki: ",
  "Haikyu!!": "Haikyu: ",
  "That Time I Get ReIncarnated As A Slime": "Slime: ",
  "Re Zero": "Re:Zero: ",
  Fate: "TypeMoon: ",
  Gate: "Gate: ",
  "Steins Gate": "Steins Gate: ",
  "Literature Club": "DDLC: ",
  KonoSuba: "KonoSuba: ",
  "Love Live": "Love Live: ",
  OreGairu: "OreGairu: ",
  OreImo: "OreImo: ",
  "EroManga Sensei": "EroManga: ",
  "Miss Kobayashi's Dragon Maid": "DM: ",
  "Darling in the Franxx": "Franxx: ",
  "The Great Jahy Will Not Be Defeated": "JahySama: ",
  "Bunny Senpai": "BunnySenpai: ",
  "Quintessential Quintuplets": "QQ: ",
  "Type-Moon": "TypeMoon: ",
  "Daily Life With A Monster Girl": "MonsterMusume: ",
  Vocaloid: "Vocaloid: ",
  Mistress: "Miss: ",
  DanganRonpa: "DR: ",
  Evangelion: "EVA: ",
  Miscellaneous: "Misc: ",
  "High School DxD": "DxD: ",
  "Sword Art Online": "SAO: ",
  "Lucky Star": "LS: ",
  "Future Diary": "FutureDiary: ",
  Kakegurui: "Kakegurui: ",
  Monogatari: "Monogatari: ",
  "Don't Toy with me Miss Nagatoro": "DTWMMN: ",
  "Yuru Camp": "YuruCamp: ",
  "NekoPara": "NekoPara: ",
};
